version: "3"

services:
  traefik:
    image: traefik:v2.11
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8081
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dev/traefik.yml:/etc/traefik/traefik.yml
      - .:/plugins-local/src/github.com/SIB-rennes/traefik_query_sticky
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.127.0.0.1.nip.io`)" 
        - "traefik.http.routers.traefik-dashboard.entrypoints=web"
        - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"


  whoami:
    image: traefik/whoami
    hostname: "whoami-{{.Task.Slot}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.127.0.0.1.nip.io`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.middlewares=whoami-plugin"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky=true"
        - "traefik.http.services.whoami.loadbalancer.sticky.cookie.name=traefik_collabora_sticky"
        # Plugin config
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky.cookieName=traefik_collabora_sticky"
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky.queryName=WOPISrc"
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky.redisAddr=redis:6379"
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky.redisDb=2"
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky.redisConnectionTimeout=1"
        - "traefik.http.middlewares.whoami-plugin.plugin.traefik_query_sticky.redisTTL=2"
      replicas: 3

  redis:
    image: redis:7.4.2
    ports:
      - "60379:6379"

networks:
  app_network:
    driver: overlay
    attachable: true