entryPoints:
  web:
    address: ":80"

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

experimental:
  localPlugins:
    traefik-wopisrc-plugin:
      moduleName: github.com/SIB-rennes/traefik-wopisrc-plugin


providers:
  docker:
    swarmMode: true
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false