entryPoints:
  web:
    address: ":80"

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

experimental:
  localPlugins:
    traefik_query_sticky:
      moduleName: github.com/SIB-rennes/traefik_query_sticky


providers:
  docker:
    swarmMode: true
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false