http:
  routers:
    test:
      rule: "Path(`/test`)"
      service: test-svc
      middlewares:
        - wopisrc-sticky

  services:
    test-svc:
      loadBalancer:
        servers:
          - url: "http://echo"

  middlewares:
    wopisrc-sticky:
      plugin:
        wopisrcsticky:
          cookieName: "traefik_collabora_sticky"